"use client"

import { createContext, useContext, useState, ReactNode } from "react"

type Language = "English" | "Kinyarwanda" | "French"

const translations = {
  English: {
    // Header
    home: "Home",
    findBuses: "Find Buses",
    myTickets: "My Tickets",
    help: "Help",
    login: "Login",
    logout: "Logout",
    bookNow: "Book Now",
    profile: "Profile",
    // Hero
    badge: "Rwanda's Digital Transport Solution",
    heroTitle1: "Book your bus ticket",
    heroTitle2: "anytime, anywhere",
    heroSubtitle: "Skip the queues. Search buses, select your seat, pay online, and receive digital tickets with QR codes instantly.",
    from: "From",
    to: "To",
    date: "Date",
    passengers: "Passengers",
    findBusesBtn: "Find Available Buses",
    dailyDepartures: "Daily Departures",
    routesAvailable: "Routes Available",
    busOperators: "Bus Operators",
    citiesServed: "Cities Served",
    // Features
    whyChoose: "Why Choose BUS CONNECT?",
    whySubtitle: "Experience the future of bus travel with our comprehensive digital booking platform.",
    easySearch: "Easy Search",
    easySearchDesc: "Find buses by route, date, and time with our intuitive search system.",
    securePayments: "Secure Payments",
    securePaymentsDesc: "Pay safely with MTN MoMo, Airtel Money, or card payments.",
    digitalTickets: "Digital Tickets",
    digitalTicketsDesc: "Receive instant QR code tickets directly to your device.",
    realTimeUpdates: "Real-time Updates",
    realTimeUpdatesDesc: "Get live updates on bus schedules and seat availability.",
    verifiedCompanies: "Verified Companies",
    verifiedCompaniesDesc: "Travel with trusted and verified bus operators.",
    support247: "24/7 Support",
    support247Desc: "Our customer support team is always here to help.",
    // Footer
    footerDesc: "Rwanda's leading digital bus ticket booking platform. Travel smarter, book faster.",
    quickLinks: "Quick Links",
    popularRoutes: "Popular Routes",
    forBusiness: "For Business",
    registerCompany: "Register Your Company",
    companyDashboard: "Company Dashboard",
    adminDashboard: "Admin Dashboard",
    supportFooter: "Support",
    faq: "FAQ",
    contactUs: "Contact Us",
    terms: "Terms & Conditions",
    allRights: "All rights reserved.",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    // Search results
    availableBuses: "Available Buses",
    resultsSummary: "{slots} departures found across {lines} bus lines",
    departures: "departures",
    seatsLeft: "seats left",
    selectSeatsBtn: "Select Seats",
    searchingBuses: "Searching for available buses...",
    noBusesTitle: "No buses on this route",
    noBusesBody:
      "No operator has published a departure from {from} to {to} yet. Try another route, or leave both fields empty to see every available trip.",
    anywhere: "anywhere",
    allDepartedTitle: "Today's buses have already left",
    allDepartedBody:
      "Every departure on this route has gone for today. Search tomorrow's date to see the next available trips.",
    // Seat selection
    selectYourSeats: "Select Your Seats",
    checkingSeats: "Checking seat availability...",
    seatsAvailableOf: "{available} of {total} seats available",
    chooseUpTo: "choose up to {max}",
    seatAvailable: "Available",
    seatSelected: "Selected",
    seatTaken: "Taken",
    driver: "Driver",
    selectedSeats: "Selected Seats",
    noSeatsSelected: "No seats selected",
    totalPrice: "Total Price",
    proceedToPayment: "Proceed to Payment",
    fullyBooked: "This bus is fully booked for {date}. Please choose another departure.",
    seatLimitReached: "Seat limit reached for {max} passenger(s).",
    seatCheckFailed: "Could not check which seats are taken. Showing all as available.",
    // Payment
    completePayment: "Complete Payment",
    secureCheckout: "Secure checkout",
    orderSummary: "Order Summary",
    routeLabel: "Route",
    busCompanyLabel: "Bus Company",
    departureLabel: "Departure",
    seatsLabel: "Seats",
    totalLabel: "Total",
    passengerDetails: "Passenger Details",
    fullNameLabel: "Full name",
    fullNamePlaceholder: "As it appears on your ID",
    phoneLabel: "Phone number",
    phoneHelp: "Used to confirm your booking and for mobile money payment.",
    nameRequired: "Passenger name is required",
    phoneRequired: "Phone number is required",
    phoneInvalid: "Enter a valid phone number",
    paymentMethodLabel: "Payment Method",
    mtnMoMo: "MTN Mobile Money",
    payWithMtn: "Pay with MTN MoMo",
    airtelMoney: "Airtel Money",
    payWithAirtel: "Pay with Airtel Money",
    cardPayment: "Debit/Credit Card",
    cardTypes: "Visa, Mastercard",
    paymentRequestNote: "A payment request will be sent to {phone}.",
    yourPhoneNumber: "your phone number",
    payAmount: "Pay {amount} RWF",
    processing: "Processing...",
    paymentSuccessful: "Payment Successful!",
    ticketConfirmed: "Your ticket has been confirmed. Redirecting to your ticket...",
    paymentSecureNote: "Your payment is secure and encrypted",
    bookingFailed: "Your booking could not be saved. Please choose your seats again.",
    // Ticket
    digitalBusTicket: "Digital Bus Ticket",
    confirmed: "Confirmed",
    ticketNo: "Ticket",
    passengerLabel: "Passenger",
    travelDateLabel: "Travel Date",
    seatLabelPlural: "Seat(s)",
    ticketIdLabel: "Ticket ID",
    pinLabel: "PIN",
    saveTicketNote:
      "Save or share this ticket now. You need the ID and PIN to open it again under My Tickets.",
    showQrNote: "Show this QR code at the station",
    qrUnavailable: "QR unavailable - use the ticket ID",
    totalPaid: "Total Paid",
    download: "Download",
    share: "Share",
    // Ticket lookup
    findYourTicket: "Find your ticket",
    findTicketHelp: "Enter the ticket ID and PIN from the ticket you received after paying.",
    findMyTicket: "Find my ticket",
    searchingTicket: "Searching...",
    ticketNotFound: "No ticket matches that ID and PIN. Check both and try again.",
    lookupFailed: "Could not look up your ticket. Please try again.",
    lookUpAnother: "Look up another ticket",
    reschedule: "Reschedule",
    close: "Close",
    stateValid: "Valid",
    stateValidDetail: "This ticket has not been used yet and can still be scanned at the gate.",
    stateUsed: "Used",
    stateUsedDetail: "This ticket was scanned and the passenger has boarded.",
    stateExpired: "Expired",
    stateExpiredDetail: "The departure time has passed and this ticket was never used.",
    stateCancelled: "Cancelled",
    stateCancelledDetail: "This booking was cancelled and cannot be used.",
    // Reschedule
    rescheduleTicket: "Reschedule Ticket",
    currentDeparture: "Current departure",
    rescheduleFeeNote:
      "A reschedule fee of {fee} RWF applies. You keep your seat numbers, so they must be free on the new departure.",
    otherDepartures: "Other departures that day",
    loadingDepartures: "Loading departures...",
    noOtherDepartures:
      "{company} has no other departure published on this route. Rescheduling is only possible onto another of their trips.",
    seatTakenOnDeparture: "Seat {seats} already taken",
    seatMissingOnBus: "Seat {seats} does not exist on this bus",
    noFareChange: "No fare change",
    rescheduleSummary: "Reschedule Summary",
    oldDeparture: "Old departure",
    newDeparture: "New departure",
    rescheduleFeeLabel: "Reschedule fee",
    fareDifference: "Fare difference",
    totalDue: "Total due",
    continueBtn: "Continue",
    back: "Back",
    rescheduledTitle: "Rescheduled!",
    rescheduledBody: "Your ticket has been moved to {time}.",
    rescheduleFailed: "Failed to reschedule. Please try again.",
  },
  Kinyarwanda: {
    home: "Ahabanza",
    findBuses: "Shakisha Bisi",
    myTickets: "Tiketi Zanjye",
    help: "Ubufasha",
    login: "Injira",
    logout: "Sohoka",
    bookNow: "Bika Ubu",
    profile: "Umwirondoro",
    badge: "Igisubizo cy'Ingendo mu Rwanda",
    heroTitle1: "Bika tiketi ya bisi yawe",
    heroTitle2: "igihe cyose, aho waba uri hose",
    heroSubtitle: "Reka gutegereza mu murongo. Shakisha bisi, hitamo intebe yawe, wishyure kuri interineti, ubone tiketi ya dijitali hamwe na QR code vuba.",
    from: "Uvuye",
    to: "Ujya",
    date: "Itariki",
    passengers: "Abagenzi",
    findBusesBtn: "Shakisha Bisi Zihari",
    dailyDepartures: "Ingendo za Buri Munsi",
    routesAvailable: "Inzira Zihari",
    busOperators: "Sosiyete za Bisi",
    citiesServed: "Imijyi Ikorerwamo",
    whyChoose: "Kubera iki Uhitamo BUS CONNECT?",
    whySubtitle: "Menya ejo hazaza h'ingendo za bisi hamwe na platform yacu ya dijitali.",
    easySearch: "Gushakisha Byoroshye",
    easySearchDesc: "Shakisha bisi ukurikije inzira, itariki, n'igihe hamwe na sisitemu yacu yoroshye.",
    securePayments: "Kwishyura Mu Mutekano",
    securePaymentsDesc: "Ishyura mu mutekano na MTN MoMo, Airtel Money, cyangwa ikarita.",
    digitalTickets: "Tiketi za Dijitali",
    digitalTicketsDesc: "Bona tiketi za QR code vuba kuri telefone yawe.",
    realTimeUpdates: "Amakuru Ahora Ashya",
    realTimeUpdatesDesc: "Bona amakuru mashya ku gahunda za bisi n'intebe zihari.",
    verifiedCompanies: "Sosiyete Zemejwe",
    verifiedCompaniesDesc: "Genda na sosiyete za bisi zizewe kandi zemejwe.",
    support247: "Ubufasha 24/7",
    support247Desc: "Itsinda ryacu ry'ubufasha bw'abakiriya rihoraho gufasha.",
    footerDesc: "Platform nziza ya dijitali yo kubika tiketi za bisi mu Rwanda. Genda neza, buka vuba.",
    quickLinks: "Itumanaho Ryihuse",
    popularRoutes: "Inzira Zikunzwe",
    forBusiness: "Ku Bikorwa",
    registerCompany: "Andika Sosiyete Yawe",
    companyDashboard: "Ikibaho cya Sosiyete",
    adminDashboard: "Ikibaho cy'Umuyobozi",
    supportFooter: "Ubufasha",
    faq: "Ibibazo Bikunzwe",
    contactUs: "Twandikire",
    terms: "Amategeko n'Amabwiriza",
    allRights: "Uburenganzira bwose bwihariwe.",
    privacyPolicy: "Politiki y'Ubuzima bwite",
    termsOfService: "Amategeko y'Ibikorwa",
    // Search results
    availableBuses: "Bisi Zihari",
    resultsSummary: "Ingendo {slots} zabonetse muri sosiyete {lines}",
    departures: "ingendo",
    seatsLeft: "intebe zisigaye",
    selectSeatsBtn: "Hitamo Intebe",
    searchingBuses: "Turashakisha bisi zihari...",
    noBusesTitle: "Nta bisi ziri kuri iyi nzira",
    noBusesBody:
      "Nta sosiyete iratangaza urugendo ruva {from} rujya {to}. Gerageza indi nzira, cyangwa usige imyanya yombi ubusa kugira ngo ubone ingendo zose zihari.",
    anywhere: "ahantu hose",
    allDepartedTitle: "Bisi z'uyu munsi zamaze kugenda",
    allDepartedBody:
      "Ingendo zose zo kuri iyi nzira zamaze kugenda uyu munsi. Shakisha itariki y'ejo kugira ngo ubone ingendo zikurikira.",
    // Seat selection
    selectYourSeats: "Hitamo Intebe Yawe",
    checkingSeats: "Turareba intebe zihari...",
    seatsAvailableOf: "Intebe {available} kuri {total} zirahari",
    chooseUpTo: "hitamo kugeza kuri {max}",
    seatAvailable: "Irahari",
    seatSelected: "Yatoranyijwe",
    seatTaken: "Yarafashwe",
    driver: "Umushoferi",
    selectedSeats: "Intebe Watoranyije",
    noSeatsSelected: "Nta ntebe yatoranyijwe",
    totalPrice: "Igiciro Cyose",
    proceedToPayment: "Komeza Wishyure",
    fullyBooked: "Iyi bisi yuzuye kuri {date}. Hitamo urundi rugendo.",
    seatLimitReached: "Wageze ku ntebe zemewe ku bagenzi {max}.",
    seatCheckFailed: "Ntibishobotse kureba intebe zafashwe. Zose zerekanwe nk'izihari.",
    // Payment
    completePayment: "Uzuza Kwishyura",
    secureCheckout: "Kwishyura mu mutekano",
    orderSummary: "Incamake y'Ubwishyu",
    routeLabel: "Inzira",
    busCompanyLabel: "Sosiyete ya Bisi",
    departureLabel: "Kugenda",
    seatsLabel: "Intebe",
    totalLabel: "Byose",
    passengerDetails: "Amakuru y'Umugenzi",
    fullNameLabel: "Amazina yombi",
    fullNamePlaceholder: "Nk'uko ari ku ndangamuntu yawe",
    phoneLabel: "Nimero ya telefone",
    phoneHelp: "Ikoreshwa mu kwemeza ubwishyu bwawe no kwishyura kuri telefone.",
    nameRequired: "Amazina y'umugenzi arakenewe",
    phoneRequired: "Nimero ya telefone irakenewe",
    phoneInvalid: "Andika nimero ya telefone yemewe",
    paymentMethodLabel: "Uburyo bwo Kwishyura",
    mtnMoMo: "MTN Mobile Money",
    payWithMtn: "Ishyura na MTN MoMo",
    airtelMoney: "Airtel Money",
    payWithAirtel: "Ishyura na Airtel Money",
    cardPayment: "Ikarita ya Banki",
    cardTypes: "Visa, Mastercard",
    paymentRequestNote: "Ubusabe bwo kwishyura buzoherezwa kuri {phone}.",
    yourPhoneNumber: "nimero ya telefone yawe",
    payAmount: "Ishyura {amount} RWF",
    processing: "Birimo gutunganywa...",
    paymentSuccessful: "Kwishyura Byagenze Neza!",
    ticketConfirmed: "Tiketi yawe yemejwe. Turakujyana kuri tiketi yawe...",
    paymentSecureNote: "Ubwishyu bwawe buri mu mutekano kandi bufite ubwirinzi",
    bookingFailed: "Ubwishyu bwawe ntibwabitswe. Ongera uhitemo intebe.",
    // Ticket
    digitalBusTicket: "Tiketi ya Bisi ya Dijitali",
    confirmed: "Byemejwe",
    ticketNo: "Tiketi",
    passengerLabel: "Umugenzi",
    travelDateLabel: "Itariki y'Urugendo",
    seatLabelPlural: "Intebe",
    ticketIdLabel: "Nimero ya Tiketi",
    pinLabel: "PIN",
    saveTicketNote:
      "Bika cyangwa usangize iyi tiketi ubu. Ukeneye nimero na PIN kugira ngo wongere uyifungure muri Tiketi Zanjye.",
    showQrNote: "Erekana iyi QR code ku isitasiyo",
    qrUnavailable: "QR ntiboneka - koresha nimero ya tiketi",
    totalPaid: "Byishyuwe Byose",
    download: "Kuramo",
    share: "Sangiza",
    // Ticket lookup
    findYourTicket: "Shakisha tiketi yawe",
    findTicketHelp: "Andika nimero na PIN biri kuri tiketi wahawe nyuma yo kwishyura.",
    findMyTicket: "Shakisha tiketi yanjye",
    searchingTicket: "Turashakisha...",
    ticketNotFound: "Nta tiketi ihuye n'iyo nimero na PIN. Reba byombi wongere ugerageze.",
    lookupFailed: "Ntibishobotse gushakisha tiketi yawe. Ongera ugerageze.",
    lookUpAnother: "Shakisha indi tiketi",
    reschedule: "Hindura Igihe",
    close: "Funga",
    stateValid: "Ikora",
    stateValidDetail: "Iyi tiketi ntiyakoreshejwe kandi iracyashobora gusomwa ku muryango.",
    stateUsed: "Yakoreshejwe",
    stateUsedDetail: "Iyi tiketi yasomwe kandi umugenzi yarinjiye muri bisi.",
    stateExpired: "Yarangiye",
    stateExpiredDetail: "Igihe cyo kugenda cyarangiye kandi iyi tiketi ntiyakoreshejwe.",
    stateCancelled: "Yahagaritswe",
    stateCancelledDetail: "Ubu bwishyu bwarahagaritswe kandi ntibushobora gukoreshwa.",
    // Reschedule
    rescheduleTicket: "Hindura Igihe cya Tiketi",
    currentDeparture: "Igihe cyo kugenda ubu",
    rescheduleFeeNote:
      "Hakenewe amafaranga yo guhindura igihe angana na {fee} RWF. Ugumana intebe zawe, bityo zigomba kuba zihari mu rugendo rushya.",
    otherDepartures: "Izindi ngendo z'uwo munsi",
    loadingDepartures: "Turashakisha ingendo...",
    noOtherDepartures:
      "{company} nta rundi rugendo yatangaje kuri iyi nzira. Guhindura igihe bishoboka gusa mu zindi ngendo zabo.",
    seatTakenOnDeparture: "Intebe {seats} yarafashwe",
    seatMissingOnBus: "Intebe {seats} ntibaho kuri iyi bisi",
    noFareChange: "Nta mpinduka ku giciro",
    rescheduleSummary: "Incamake yo Guhindura Igihe",
    oldDeparture: "Igihe cya kera",
    newDeparture: "Igihe gishya",
    rescheduleFeeLabel: "Amafaranga yo guhindura",
    fareDifference: "Itandukaniro ry'igiciro",
    totalDue: "Byose ugomba kwishyura",
    continueBtn: "Komeza",
    back: "Subira inyuma",
    rescheduledTitle: "Igihe Cyahinduwe!",
    rescheduledBody: "Tiketi yawe yimuriwe kuri {time}.",
    rescheduleFailed: "Guhindura igihe ntibyakunze. Ongera ugerageze.",
  },
  French: {
    home: "Accueil",
    findBuses: "Trouver des Bus",
    myTickets: "Mes Billets",
    help: "Aide",
    login: "Connexion",
    logout: "Déconnexion",
    bookNow: "Réserver",
    profile: "Profil",
    badge: "Solution de Transport Numérique du Rwanda",
    heroTitle1: "Réservez votre billet de bus",
    heroTitle2: "n'importe quand, n'importe où",
    heroSubtitle: "Évitez les files d'attente. Recherchez des bus, choisissez votre siège, payez en ligne et recevez des billets numériques avec QR codes instantanément.",
    from: "De",
    to: "À",
    date: "Date",
    passengers: "Passagers",
    findBusesBtn: "Trouver des Bus Disponibles",
    dailyDepartures: "Départs Quotidiens",
    routesAvailable: "Itinéraires Disponibles",
    busOperators: "Compagnies de Bus",
    citiesServed: "Villes Desservies",
    whyChoose: "Pourquoi Choisir BUS CONNECT?",
    whySubtitle: "Découvrez l'avenir du voyage en bus avec notre plateforme de réservation numérique complète.",
    easySearch: "Recherche Facile",
    easySearchDesc: "Trouvez des bus par itinéraire, date et heure avec notre système intuitif.",
    securePayments: "Paiements Sécurisés",
    securePaymentsDesc: "Payez en toute sécurité avec MTN MoMo, Airtel Money ou carte bancaire.",
    digitalTickets: "Billets Numériques",
    digitalTicketsDesc: "Recevez instantanément des billets QR code directement sur votre appareil.",
    realTimeUpdates: "Mises à Jour en Temps Réel",
    realTimeUpdatesDesc: "Obtenez des mises à jour en direct sur les horaires et la disponibilité des sièges.",
    verifiedCompanies: "Compagnies Vérifiées",
    verifiedCompaniesDesc: "Voyagez avec des opérateurs de bus de confiance et vérifiés.",
    support247: "Support 24/7",
    support247Desc: "Notre équipe de support client est toujours là pour vous aider.",
    footerDesc: "La principale plateforme numérique de réservation de billets de bus au Rwanda. Voyagez plus intelligemment, réservez plus vite.",
    quickLinks: "Liens Rapides",
    popularRoutes: "Itinéraires Populaires",
    forBusiness: "Pour les Entreprises",
    registerCompany: "Enregistrer Votre Entreprise",
    companyDashboard: "Tableau de Bord Entreprise",
    adminDashboard: "Administration",
    supportFooter: "Support",
    faq: "FAQ",
    contactUs: "Contactez-nous",
    terms: "Conditions Générales",
    allRights: "Tous droits réservés.",
    privacyPolicy: "Politique de Confidentialité",
    termsOfService: "Conditions d'Utilisation",
    // Search results
    availableBuses: "Bus Disponibles",
    resultsSummary: "{slots} départs trouvés chez {lines} compagnies",
    departures: "départs",
    seatsLeft: "sièges restants",
    selectSeatsBtn: "Choisir les Sièges",
    searchingBuses: "Recherche des bus disponibles...",
    noBusesTitle: "Aucun bus sur cet itinéraire",
    noBusesBody:
      "Aucun opérateur n'a encore publié de départ de {from} vers {to}. Essayez un autre itinéraire, ou laissez les deux champs vides pour voir tous les trajets disponibles.",
    anywhere: "partout",
    allDepartedTitle: "Les bus d'aujourd'hui sont déjà partis",
    allDepartedBody:
      "Tous les départs sur cet itinéraire sont partis pour aujourd'hui. Cherchez la date de demain pour voir les prochains trajets.",
    // Seat selection
    selectYourSeats: "Choisissez Vos Sièges",
    checkingSeats: "Vérification des sièges disponibles...",
    seatsAvailableOf: "{available} sièges disponibles sur {total}",
    chooseUpTo: "choisissez jusqu'à {max}",
    seatAvailable: "Disponible",
    seatSelected: "Sélectionné",
    seatTaken: "Occupé",
    driver: "Chauffeur",
    selectedSeats: "Sièges Sélectionnés",
    noSeatsSelected: "Aucun siège sélectionné",
    totalPrice: "Prix Total",
    proceedToPayment: "Procéder au Paiement",
    fullyBooked: "Ce bus est complet pour le {date}. Veuillez choisir un autre départ.",
    seatLimitReached: "Limite atteinte pour {max} passager(s).",
    seatCheckFailed:
      "Impossible de vérifier les sièges occupés. Tous sont affichés comme disponibles.",
    // Payment
    completePayment: "Finaliser le Paiement",
    secureCheckout: "Paiement sécurisé",
    orderSummary: "Récapitulatif",
    routeLabel: "Itinéraire",
    busCompanyLabel: "Compagnie de Bus",
    departureLabel: "Départ",
    seatsLabel: "Sièges",
    totalLabel: "Total",
    passengerDetails: "Informations du Passager",
    fullNameLabel: "Nom complet",
    fullNamePlaceholder: "Tel qu'il figure sur votre pièce d'identité",
    phoneLabel: "Numéro de téléphone",
    phoneHelp: "Utilisé pour confirmer votre réservation et pour le paiement mobile.",
    nameRequired: "Le nom du passager est requis",
    phoneRequired: "Le numéro de téléphone est requis",
    phoneInvalid: "Entrez un numéro de téléphone valide",
    paymentMethodLabel: "Mode de Paiement",
    mtnMoMo: "MTN Mobile Money",
    payWithMtn: "Payer avec MTN MoMo",
    airtelMoney: "Airtel Money",
    payWithAirtel: "Payer avec Airtel Money",
    cardPayment: "Carte Bancaire",
    cardTypes: "Visa, Mastercard",
    paymentRequestNote: "Une demande de paiement sera envoyée au {phone}.",
    yourPhoneNumber: "votre numéro de téléphone",
    payAmount: "Payer {amount} RWF",
    processing: "Traitement en cours...",
    paymentSuccessful: "Paiement Réussi!",
    ticketConfirmed: "Votre billet est confirmé. Redirection vers votre billet...",
    paymentSecureNote: "Votre paiement est sécurisé et chiffré",
    bookingFailed: "Votre réservation n'a pas pu être enregistrée. Veuillez choisir vos sièges à nouveau.",
    // Ticket
    digitalBusTicket: "Billet de Bus Numérique",
    confirmed: "Confirmé",
    ticketNo: "Billet",
    passengerLabel: "Passager",
    travelDateLabel: "Date du Voyage",
    seatLabelPlural: "Siège(s)",
    ticketIdLabel: "Numéro du Billet",
    pinLabel: "PIN",
    saveTicketNote:
      "Enregistrez ou partagez ce billet maintenant. Le numéro et le PIN sont nécessaires pour le rouvrir dans Mes Billets.",
    showQrNote: "Présentez ce QR code à la gare",
    qrUnavailable: "QR indisponible - utilisez le numéro du billet",
    totalPaid: "Total Payé",
    download: "Télécharger",
    share: "Partager",
    // Ticket lookup
    findYourTicket: "Retrouvez votre billet",
    findTicketHelp: "Entrez le numéro et le PIN figurant sur le billet reçu après paiement.",
    findMyTicket: "Retrouver mon billet",
    searchingTicket: "Recherche...",
    ticketNotFound: "Aucun billet ne correspond à ce numéro et ce PIN. Vérifiez les deux et réessayez.",
    lookupFailed: "Impossible de retrouver votre billet. Veuillez réessayer.",
    lookUpAnother: "Rechercher un autre billet",
    reschedule: "Reporter",
    close: "Fermer",
    stateValid: "Valide",
    stateValidDetail: "Ce billet n'a pas encore été utilisé et peut être scanné à l'embarquement.",
    stateUsed: "Utilisé",
    stateUsedDetail: "Ce billet a été scanné et le passager est monté à bord.",
    stateExpired: "Expiré",
    stateExpiredDetail: "L'heure de départ est passée et ce billet n'a jamais été utilisé.",
    stateCancelled: "Annulé",
    stateCancelledDetail: "Cette réservation a été annulée et ne peut pas être utilisée.",
    // Reschedule
    rescheduleTicket: "Reporter le Billet",
    currentDeparture: "Départ actuel",
    rescheduleFeeNote:
      "Des frais de report de {fee} RWF s'appliquent. Vous conservez vos numéros de siège, ils doivent donc être libres sur le nouveau départ.",
    otherDepartures: "Autres départs ce jour-là",
    loadingDepartures: "Chargement des départs...",
    noOtherDepartures:
      "{company} n'a publié aucun autre départ sur cet itinéraire. Le report n'est possible que vers un de leurs autres trajets.",
    seatTakenOnDeparture: "Siège {seats} déjà occupé",
    seatMissingOnBus: "Le siège {seats} n'existe pas dans ce bus",
    noFareChange: "Aucun changement de tarif",
    rescheduleSummary: "Récapitulatif du Report",
    oldDeparture: "Ancien départ",
    newDeparture: "Nouveau départ",
    rescheduleFeeLabel: "Frais de report",
    fareDifference: "Différence de tarif",
    totalDue: "Total à payer",
    continueBtn: "Continuer",
    back: "Retour",
    rescheduledTitle: "Report Effectué!",
    rescheduledBody: "Votre billet a été déplacé à {time}.",
    rescheduleFailed: "Le report a échoué. Veuillez réessayer.",
  },
}

export type Translations = typeof translations.English

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: Translations
}

const LanguageContext = createContext<LanguageContextType>({
  language: "English",
  setLanguage: () => {},
  t: translations.English,
})

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("English")
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)

/**
 * Fill `{name}` placeholders in a translated string.
 *
 * Sentences are translated whole rather than assembled from fragments, because
 * word order differs between the three languages - "12 of 45 seats available"
 * and "Intebe 12 kuri 45 zirahari" put the numbers in different places.
 *
 *   format(t.seatsAvailableOf, { available: 12, total: 45 })
 */
export function format(template: string, values: Record<string, string | number>) {
  return Object.entries(values).reduce(
    (text, [key, value]) => text.replaceAll(`{${key}}`, String(value)),
    template,
  )
}
