"use client"

import { createContext, useContext, useState, ReactNode } from "react"

type Language = "English" | "Kinyarwanda" | "French"

const translations = {
  English: {
    // Header
    home: "Home",
    findBuses: "Find Buses",
    myTickets: "My Tickets",
    help: "Help",
    login: "Login",
    logout: "Logout",
    bookNow: "Book Now",
    profile: "Profile",
    // Hero
    badge: "Rwanda's Digital Transport Solution",
    heroTitle1: "Book your bus ticket",
    heroTitle2: "anytime, anywhere",
    heroSubtitle: "Skip the queues. Search buses, select your seat, pay online, and receive digital tickets with QR codes instantly.",
    from: "From",
    to: "To",
    date: "Date",
    passengers: "Passengers",
    findBusesBtn: "Find Available Buses",
    happyPassengers: "Happy Passengers",
    routesAvailable: "Routes Available",
    support: "Customer Support",
    onTime: "On-time Arrivals",
    // Features
    whyChoose: "Why Choose BUS CONNECT?",
    whySubtitle: "Experience the future of bus travel with our comprehensive digital booking platform.",
    easySearch: "Easy Search",
    easySearchDesc: "Find buses by route, date, and time with our intuitive search system.",
    securePayments: "Secure Payments",
    securePaymentsDesc: "Pay safely with MTN MoMo, Airtel Money, or card payments.",
    digitalTickets: "Digital Tickets",
    digitalTicketsDesc: "Receive instant QR code tickets directly to your device.",
    realTimeUpdates: "Real-time Updates",
    realTimeUpdatesDesc: "Get live updates on bus schedules and seat availability.",
    verifiedCompanies: "Verified Companies",
    verifiedCompaniesDesc: "Travel with trusted and verified bus operators.",
    support247: "24/7 Support",
    support247Desc: "Our customer support team is always here to help.",
    // Footer
    footerDesc: "Rwanda's leading digital bus ticket booking platform. Travel smarter, book faster.",
    quickLinks: "Quick Links",
    popularRoutes: "Popular Routes",
    forBusiness: "For Business",
    registerCompany: "Register Your Company",
    companyDashboard: "Company Dashboard",
    adminDashboard: "Admin Dashboard",
    pricing: "Pricing",
    apiAccess: "API Access",
    supportFooter: "Support",
    helpCenter: "Help Center",
    faq: "FAQ",
    contactUs: "Contact Us",
    terms: "Terms & Conditions",
    allRights: "All rights reserved.",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
  },
  Kinyarwanda: {
    home: "Ahabanza",
    findBuses: "Shakisha Bisi",
    myTickets: "Tiketi Zanjye",
    help: "Ubufasha",
    login: "Injira",
    logout: "Sohoka",
    bookNow: "Bika Ubu",
    profile: "Umwirondoro",
    badge: "Igisubizo cy'Ingendo mu Rwanda",
    heroTitle1: "Bika tiketi ya bisi yawe",
    heroTitle2: "igihe cyose, aho waba uri hose",
    heroSubtitle: "Reka gutegereza mu murongo. Shakisha bisi, hitamo intebe yawe, wishyure kuri interineti, ubone tiketi ya dijitali hamwe na QR code vuba.",
    from: "Uvuye",
    to: "Ujya",
    date: "Itariki",
    passengers: "Abagenzi",
    findBusesBtn: "Shakisha Bisi Zihari",
    happyPassengers: "Abagenzi Bashimye",
    routesAvailable: "Inzira Zihari",
    support: "Serivisi z'Abakiriya",
    onTime: "Kugera ku Gihe",
    whyChoose: "Kubera iki Uhitamo BUS CONNECT?",
    whySubtitle: "Menya ejo hazaza h'ingendo za bisi hamwe na platform yacu ya dijitali.",
    easySearch: "Gushakisha Byoroshye",
    easySearchDesc: "Shakisha bisi ukurikije inzira, itariki, n'igihe hamwe na sisitemu yacu yoroshye.",
    securePayments: "Kwishyura Mu Mutekano",
    securePaymentsDesc: "Ishyura mu mutekano na MTN MoMo, Airtel Money, cyangwa ikarita.",
    digitalTickets: "Tiketi za Dijitali",
    digitalTicketsDesc: "Bona tiketi za QR code vuba kuri telefone yawe.",
    realTimeUpdates: "Amakuru Ahora Ashya",
    realTimeUpdatesDesc: "Bona amakuru mashya ku gahunda za bisi n'intebe zihari.",
    verifiedCompanies: "Sosiyete Zemejwe",
    verifiedCompaniesDesc: "Genda na sosiyete za bisi zizewe kandi zemejwe.",
    support247: "Ubufasha 24/7",
    support247Desc: "Itsinda ryacu ry'ubufasha bw'abakiriya rihoraho gufasha.",
    footerDesc: "Platform nziza ya dijitali yo kubika tiketi za bisi mu Rwanda. Genda neza, buka vuba.",
    quickLinks: "Itumanaho Ryihuse",
    popularRoutes: "Inzira Zikunzwe",
    forBusiness: "Ku Bikorwa",
    registerCompany: "Andika Sosiyete Yawe",
    companyDashboard: "Ikibaho cya Sosiyete",
    adminDashboard: "Ikibaho cy'Umuyobozi",
    pricing: "Ibiciro",
    apiAccess: "Kwinjira kuri API",
    supportFooter: "Ubufasha",
    helpCenter: "Ikigo cy'Ubufasha",
    faq: "Ibibazo Bikunzwe",
    contactUs: "Twandikire",
    terms: "Amategeko n'Amabwiriza",
    allRights: "Uburenganzira bwose bwihariwe.",
    privacyPolicy: "Politiki y'Ubuzima bwite",
    termsOfService: "Amategeko y'Ibikorwa",
  },
  French: {
    home: "Accueil",
    findBuses: "Trouver des Bus",
    myTickets: "Mes Billets",
    help: "Aide",
    login: "Connexion",
    logout: "Déconnexion",
    bookNow: "Réserver",
    profile: "Profil",
    badge: "Solution de Transport Numérique du Rwanda",
    heroTitle1: "Réservez votre billet de bus",
    heroTitle2: "n'importe quand, n'importe où",
    heroSubtitle: "Évitez les files d'attente. Recherchez des bus, choisissez votre siège, payez en ligne et recevez des billets numériques avec QR codes instantanément.",
    from: "De",
    to: "À",
    date: "Date",
    passengers: "Passagers",
    findBusesBtn: "Trouver des Bus Disponibles",
    happyPassengers: "Passagers Satisfaits",
    routesAvailable: "Itinéraires Disponibles",
    support: "Support Client",
    onTime: "Arrivées à l'Heure",
    whyChoose: "Pourquoi Choisir BUS CONNECT?",
    whySubtitle: "Découvrez l'avenir du voyage en bus avec notre plateforme de réservation numérique complète.",
    easySearch: "Recherche Facile",
    easySearchDesc: "Trouvez des bus par itinéraire, date et heure avec notre système intuitif.",
    securePayments: "Paiements Sécurisés",
    securePaymentsDesc: "Payez en toute sécurité avec MTN MoMo, Airtel Money ou carte bancaire.",
    digitalTickets: "Billets Numériques",
    digitalTicketsDesc: "Recevez instantanément des billets QR code directement sur votre appareil.",
    realTimeUpdates: "Mises à Jour en Temps Réel",
    realTimeUpdatesDesc: "Obtenez des mises à jour en direct sur les horaires et la disponibilité des sièges.",
    verifiedCompanies: "Compagnies Vérifiées",
    verifiedCompaniesDesc: "Voyagez avec des opérateurs de bus de confiance et vérifiés.",
    support247: "Support 24/7",
    support247Desc: "Notre équipe de support client est toujours là pour vous aider.",
    footerDesc: "La principale plateforme numérique de réservation de billets de bus au Rwanda. Voyagez plus intelligemment, réservez plus vite.",
    quickLinks: "Liens Rapides",
    popularRoutes: "Itinéraires Populaires",
    forBusiness: "Pour les Entreprises",
    registerCompany: "Enregistrer Votre Entreprise",
    companyDashboard: "Tableau de Bord Entreprise",
    adminDashboard: "Administration",
    pricing: "Tarification",
    apiAccess: "Accès API",
    supportFooter: "Support",
    helpCenter: "Centre d'Aide",
    faq: "FAQ",
    contactUs: "Contactez-nous",
    terms: "Conditions Générales",
    allRights: "Tous droits réservés.",
    privacyPolicy: "Politique de Confidentialité",
    termsOfService: "Conditions d'Utilisation",
  },
}

type Translations = typeof translations.English

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: Translations
}

const LanguageContext = createContext<LanguageContextType>({
  language: "English",
  setLanguage: () => {},
  t: translations.English,
})

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("English")
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
